### ISSUE TITLE
`translation:download` command is trimming all translations

### ISSUE THREAD

**Issue by EpocDotFr** [vemcogroup/laravel-translation#11]
Hello all,

Say I have a translation in my source code which is formatted like this:

```php
trans(' with :assets', ['assets' => $assets]); // Notice the whitespace prefixing the translation
```

In the POEditor interface, when translating this sentence to another language, the aforementioned whitespace should remain. Which is perfectly fine and well-handled by POEditor. It's even giving you a visual hint about this whitespace. Example in French:

![image](https://user-images.githubusercontent.com/2053431/130761860-214f593a-420c-447f-ac46-f99c6fed7d57.png)

However, when downloading translations using the `translation:download` command, all translations are trimmed. Excerpt from the resulting `fr.json` file:

```
" with :assets": "avec :assets",
```

Looks like it's on-purpose: [src/Translation.php#L127](https://github.com/vemcogroup/laravel-translation/blob/master/src/Translation.php#L127). Why such trimming?

Thank you in advance!

**Comment by eldor** [comment]
Hi,

It's implemented to avoid whitespaces in keys in case of typos from developers.
If you need it to not trim the keys, you are welcome to make a PR with a config variable and then do the trim or not based on that variable on the mentioned line: [src/Translation.php#L127](https://github.com/vemcogroup/laravel-translation/blob/master/src/Translation.php#L127). 

Otherwise i'll see if I can implement it in the upcoming weeks.

**Comment by EpocDotFr** [comment]
Will create an MR then, thanks 👍
